In [1]:
import numpy as np

In [2]:
n1=np.array([10,20,30,40])

In [3]:
n2=np.array([100,200,300,400,500])
n2

array([100, 200, 300, 400, 500])

In [4]:
print(n2)

[100 200 300 400 500]


In [5]:
print(n1)

[10 20 30 40]


In [6]:
n1

array([10, 20, 30, 40])

In [7]:
n2=np.array([[23,54,65,90],[23,98,56,7]])

In [8]:
n2

array([[23, 54, 65, 90],
       [23, 98, 56,  7]])

In [9]:
type(n1)

numpy.ndarray

In [10]:
type(n2)

numpy.ndarray

In [11]:
n3=np.array([[4,5,6,7],[64,3,6,4],[45,34,65,76]])

In [12]:
n3

array([[ 4,  5,  6,  7],
       [64,  3,  6,  4],
       [45, 34, 65, 76]])

In [13]:
n1=np.zeros((1,3))

In [14]:
n1

array([[0., 0., 0.]])

In [15]:
n1=np.zeros((5,6))

In [16]:
n55=np.zeros((10,10))
n55

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
n1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
n1=np.ones((1,4))

In [19]:
n1

array([[1., 1., 1., 1.]])

In [20]:
n1=np.zeros((4,5))

In [21]:
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
type(n1)

numpy.ndarray

In [23]:
n1=np.zeros((10,10))

In [24]:
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
n1=np.ones((6,7))

In [26]:
print(n1)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [27]:
n1=np.full((4,4),20)

In [28]:
n1

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [29]:
n1=np.arange(20,40)

In [30]:
n1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [31]:
n2=np.arange(20,51)

In [32]:
n2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [33]:
n3=np.arange(10,101,5)

In [34]:
n3

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [35]:
import numpy as np

In [36]:
np.random.randint(1,100,10)

array([75, 85, 64,  4, 22, 93, 68, 36, 41, 34])

In [37]:
n11=np.array([[20,30,40,89],[50,60,70,56]])
n11.shape

(2, 4)

In [38]:
n11.shape=(4,2)

In [39]:
n11.shape

(4, 2)

In [40]:
n11

array([[20, 30],
       [40, 89],
       [50, 60],
       [70, 56]])

In [41]:
n11.shape=(8,1)

In [42]:
n11

array([[20],
       [30],
       [40],
       [89],
       [50],
       [60],
       [70],
       [56]])

In [43]:
n1=np.arange(10,30,2)
n1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [45]:
n2=np.random.randint(10,90,10)
n2=np.arange(40,60,2)
n2

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [46]:
n3=np.vstack((n1,n2))

In [47]:
n3

array([[10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])

In [48]:
n4=np.hstack((n1,n2))

In [49]:
n4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58])

In [50]:
n5=np.column_stack((n1,n2))

In [51]:
n5

array([[10, 40],
       [12, 42],
       [14, 44],
       [16, 46],
       [18, 48],
       [20, 50],
       [22, 52],
       [24, 54],
       [26, 56],
       [28, 58]])

In [52]:
n5=np.column_stack((n1,n2))

In [53]:
n5

array([[10, 40],
       [12, 42],
       [14, 44],
       [16, 46],
       [18, 48],
       [20, 50],
       [22, 52],
       [24, 54],
       [26, 56],
       [28, 58]])

In [54]:
n21=np.intersect1d(n1,n2)

In [55]:
n21

array([], dtype=int32)

In [56]:
n3=np.arange(20,30)

In [57]:
n3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [58]:
n1_n3_common=np.intersect1d(n1,n3)

In [59]:
n1_n3_common

array([20, 22, 24, 26, 28])

In [60]:
n1_unique=np.setdiff1d(n1,n3)

In [61]:
n1_unique

array([10, 12, 14, 16, 18])

In [64]:
n1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [65]:
n3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
n_common=np.intersect1d(n1,n3)
n_common

array([20, 22, 24, 26, 28])

In [70]:
n2_unique=np.setdiff1d(n3,n1)

In [71]:
n2_unique

array([21, 23, 25, 27, 29])

In [74]:
np.intersect1d(n1,n2)

array([], dtype=int32)

In [75]:
np.setdiff1d(n1,n2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [76]:
n11=np.arange(10,60,10)
n11

array([10, 20, 30, 40, 50])

In [77]:
n12=np.arange(100,600,100)
n12

array([100, 200, 300, 400, 500])

In [78]:
n13=np.sum([n11,n12])
n13

1650

In [66]:
n14=np.sum([n11,n12],axis=0)

In [67]:
n14

array([110, 220, 330, 440, 550])

In [68]:
n15=np.sum([n11,n12],axis=1)

In [69]:
n15

array([ 150, 1500])

In [70]:
n16=np.sum([n11,n12],axis=1)

In [71]:
n16

array([ 150, 1500])

In [72]:
n16=np.sum([n11,n12],axis=1)

In [73]:
n16

array([ 150, 1500])

In [74]:
n31=n11+2
n31

array([12, 22, 32, 42, 52])

In [75]:
n32=n11-2
n32

array([ 8, 18, 28, 38, 48])

In [76]:
n33=n12*2
n33

array([ 200,  400,  600,  800, 1000])

In [77]:
n34=n12/2
n34

array([ 50., 100., 150., 200., 250.])

In [78]:
n35=n11/2
n35

array([ 5., 10., 15., 20., 25.])

In [79]:
n11+2

array([12, 22, 32, 42, 52])

In [80]:
n11-2

array([ 8, 18, 28, 38, 48])

In [81]:
n11*2

array([ 20,  40,  60,  80, 100])

In [82]:
n11/2

array([ 5., 10., 15., 20., 25.])

In [83]:
np.mean(n11)

30.0

In [84]:
np.median(n11)

30.0

In [85]:
n11

array([10, 20, 30, 40, 50])

In [86]:
n15=np.arange(10,61,10)

In [87]:
np.mean(n15)

35.0

In [88]:
n15

array([10, 20, 30, 40, 50, 60])

In [89]:
np.std(n1)

5.744562646538029

In [90]:
np.std(n11)

14.142135623730951

In [91]:
np.median(n15)

35.0

In [92]:
np.median(n11)

30.0

In [93]:
n667=np.save("myarray",n11)

In [94]:
new_n1=np.load("myarray.npy")

In [95]:
new_n1

array([10, 20, 30, 40, 50])

In [96]:
n667

In [97]:
print(new_n1)

[10 20 30 40 50]


In [98]:
new_n1

array([10, 20, 30, 40, 50])